format = """
$username\
$directory\
$git_branch\
$git_status\
$golang\
$lua\
$java\
$nodejs\
$python\
$rust\
$docker_context\
$time\
\n [ ](129)
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:194"
style_root = "bg:42"
format = '[$user ]($style)'

[directory]
style = "bg:222"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Development" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[docker_context]
symbol = " "
style = "bg:32"
format = '[ $symbol $context ]($style) $path'

[git_branch]
symbol = ""
style = "bg:195 bold 239"
format = '[ $symbol $branch ]($style)'

# [git_status]
# style = "bg:195 bold purple"
# format = '[$all_status$ahead_behind ]($style)'

[git_status]
style="bg:195"
conflicted = "ﰸ (bg:195 red)"
ahead = " (bg:195 red)"
behind = " (bg:195 red)"
diverged = "[] (bg:195 9)"
up_to_date = "[ ](bg:195 34)"
untracked = "[ ](bg:195 9)"
stashed = "[ ](bg:195 208)"
modified = "[ ](bg:195 9)"
staged = '[++\($count\)](bg:195 34)'
deleted = "[] (bg:195 9)"
format = '([$all_status$ahead_behind]($style))'

[golang]
symbol = " "
style = "bg:189"
format = '[ $symbol ($version) ]($style)'

[lua]
symbol = " "
style = "bg:25 fg:15"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:189"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:79"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style = "bg:143"
format = '[ $symbol ($version) (\($virtualenv\)) ]($style)'

[rust]
symbol = ""
style = "bg:189"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:254"
format = '[ $time ]($style)'
